# fly.toml app configuration file generated for ynabunq on 2024-02-04T15:41:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ynabunq'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
source = 'ynabunq_volume'
destination = '/app/data'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
