name: 'Run tests'

on:
  push:
    workflow_dispatch:

jobs:
  unit-tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: 'Setup environment'
        run: yarn
      - name: 'Run unit tests'
        run: yarn test:unit
  integration-tests:
    name: 'Integration tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: 'Setup environment'
        run: yarn
      - name: 'Run integration tests'
        run: yarn test:integration
