name: 'Run tests'

on:
  push:
    workflow_dispatch:

jobs:
  unit-tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    environment: Testing
    env:
      BUNQ_API_PATH: ${{ vars.BUNQ_API_PATH }}
      BUNQ_API_TOKEN: ${{ secrets.BUNQ_API_TOKEN }}
      BUNQ_INSTALLATION_TOKEN: ${{ secrets.BUNQ_INSTALLATION_TOKEN }}
      BUNQ_MONETARY_ACCOUNT_ID: ${{ secrets.BUNQ_MONETARY_ACCOUNT_ID }}
      YNAB_ACCOUNT_ID: ${{ secrets.YNAB_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: 'Setup environment'
        run: yarn
      - name: 'Run unit tests'
        run: yarn test:unit
  integration-tests:
    name: 'Integration tests'
    runs-on: ubuntu-latest
    environment: Testing
    env:
      BUNQ_API_PATH: ${{ vars.BUNQ_API_PATH }}
      BUNQ_API_TOKEN: ${{ secrets.BUNQ_API_TOKEN }}
      BUNQ_INSTALLATION_TOKEN: ${{ secrets.BUNQ_INSTALLATION_TOKEN }}
      BUNQ_MONETARY_ACCOUNT_ID: ${{ secrets.BUNQ_MONETARY_ACCOUNT_ID }}
      YNAB_ACCOUNT_ID: ${{ secrets.YNAB_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: 'Setup environment'
        run: yarn
      - name: 'Run integration tests'
        run: yarn test:integration
